# Copyright 2025 The Cross-Media Measurement Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "Build and Deploy cloud functions"

on:
  push:
    branches:
      - marcopremier/mount_datawatcher_certs_as_secrets
  workflow_dispatch:
    inputs:
      environment:
        description: "GitHub-managed environment"
        type: string
        required: true
        default: dev
  workflow_call:
    inputs:
      environment:
        description: "GitHub-managed environment"
        type: string
        required: true
        default: dev

permissions:
  id-token: write

jobs:
  build-and-deploy-cloud-functions:
    runs-on: ubuntu-22.04
#    environment: ${{ inputs.environment }}
    environment: "dev"
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.TF_SERVICE_ACCOUNT }}

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.GCLOUD_PROJECT }}

      - name: Build DataWatcherFunction
        run: >
          bazel build
          //src/main/kotlin/org/wfanet/measurement/securecomputation/deploy/gcloud/datawatcher:DataWatcherFunction

      - name: Build Bazel fat JAR
        run: >
          bazel build
          //src/main/kotlin/org/wfanet/measurement/securecomputation/deploy/gcloud/datawatcher:DataWatcherFunction_deploy.jar

      - name: Copy fat JAR to temp directory
        run: |
          mkdir -p "$RUNNER_TEMP/data_watcher_source"
          cp bazel-bin/src/main/kotlin/org/wfanet/measurement/securecomputation/deploy/gcloud/datawatcher/DataWatcherFunction_deploy.jar "$RUNNER_TEMP/data_watcher_source"

      - name: Deploy Data Watcher
        env:
          GCLOUD_REGION: ${{ vars.GCLOUD_REGION }}
          SECURE_COMPUTATION_PUBLIC_API_TARGET: ${{ vars.SECURE_COMPUTATION_PUBLIC_API_TARGET }}
          DATA_WATCHER_TRIGGER_BUCKET: ${{ vars.SECURE_COMPUTATION_BUCKET }}
          DATA_WATCHER_SERVICE_ACCOUNT: ${{ vars.DATA_WATCHER_SERVICE_ACCOUNT }}
          DATA_WATCHER_TRIGGER_SERVICE_ACCOUNT: ${{ vars.DATA_WATCHER_TRIGGER_SERVICE_ACCOUNT }}
          DATA_WATCHER_TLS_PEM_SECRET: ${{ vars.DATA_WATCHER_TLS_PEM_SECRET }}
          DATA_WATCHER_TLS_KEY_SECRET: ${{ vars.DATA_WATCHER_TLS_KEY_SECRET }}
          SECURE_COMPUTATION_ROOT_SECRET: ${{ vars.SECURE_COMPUTATION_ROOT_SECRET }}
        run: >
          gcloud functions deploy data-watcher
          --gen2
          --runtime=java17
          --entry-point=org.wfanet.measurement.securecomputation.deploy.gcloud.datawatcher.DataWatcherFunction
          --memory=512MB
          --region=$GCLOUD_REGION
          --allow-unauthenticated
          --trigger-event-filters='type=google.cloud.storage.object.v1.finalized'
          --trigger-event-filters="bucket=$DATA_WATCHER_TRIGGER_BUCKET"
          --source="$RUNNER_TEMP/data_watcher_source"
          --run-service-account=$DATA_WATCHER_SERVICE_ACCOUNT
          --trigger-service-account=$DATA_WATCHER_TRIGGER_SERVICE_ACCOUNT
          --set-env-vars="CERT_FILE_PATH=/secrets/certs/data_watcher_tls.pem,PRIVATE_KEY_FILE_PATH=/secrets/certs/data_watcher_tls.key,CERT_COLLECTION_FILE_PATH=/secrets/certs/secure_computation_root.pem,CONTROL_PLANE_TARGET=$SECURE_COMPUTATION_PUBLIC_API_TARGET,CONTROL_PLANE_CERT_HOST=data-watcher.secure-computation.dev.halo-cmm.org"
          --set-secrets=/secrets/certs/data_watcher_tls.pem=$DATA_WATCHER_TLS_PEM_SECRET:latest,\
          /secrets/certs/data_watcher_tls.key=$DATA_WATCHER_TLS_KEY_SECRET:latest,\
          /secrets/certs/secure_computation_root.pem=$SECURE_COMPUTATION_ROOT_SECRET:latest
