# Copyright 2026 The Cross-Media Measurement Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Create tracking issue for code scanning alerts

on:
  # DO_NOT_SUBMIT: remove pr event (for testing)
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-test:
    name: Create tracking issue
    runs-on: ubuntu-22.04
    permissions:
      security-events: read    
    env:
      GH_TOKEN: ${{ github.token }}
      JSON_FILE: "code-scanning-alerts.json"
    steps:
      - name: Check out revision
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Download code scanning alerts
        env:
          REF: "refs/tags/nightly/20260120.1"
        run: |
          set -euo pipefail

          for severity in critical high; do
            gh api \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              "/repos/world-federation-of-advertisers/cross-media-measurement/code-scanning/alerts" \
              --method GET \
              --paginate \
              --raw-field ref="${REF}" \
              --raw-field tool_name="Trivy" \
              --raw-field per_page="100" \
              --raw-field severity="${severity}" >> "${JSON_FILE}"
          done
          cat "${JSON_FILE}"

      - name: Create tracking issue
        env:
          RULE_ID: "CVE-2026-0861"
        run: |
          set -euo pipefail

          ids=$(cat ${JSON_FILE} | jq '.[] | [.number, .rule.id] | @csv' -rc | grep ${RULE_ID} | cut -d "," -f1)

          # compute title
          first_id=$(echo "${ids}" | head -n1)
          title=$(cat "${JSON_FILE}" | jq --arg TARGET_ID "${first_id}" '.[] | select(.number == ($TARGET_ID | tonumber)) | .rule.description' -rc)

          echo "Fix code scanning alert - ${RULE_ID} - ${title}"
          echo 
          echo "Vulnerability: [${RULE_ID}](https://nvd.nist.gov/vuln/detail/$RULE_ID)"
          echo
          echo "Tracking issue for:"
          for id in ${ids}; do
            echo "- https://github.com/world-federation-of-advertisers/cross-media-measurement/security/code-scanning/$id"
          done